version: '3.9'
services:
  postgres:
    image: postgres:16
    container_name: yahala-postgres
    environment:
      POSTGRES_DB: yahala
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - yahala_pg_data:/var/lib/postgresql/data
volumes:
  yahala_pg_data:
